// Interactive Bible Map — Location Data
// KJV text is public domain. No license required.

const LOCATIONS = {

  acts: [
    {
      id: 0,
      section: "acts",
      sequence: 0,
      type: "narrative",
      name: "Jerusalem",
      modernName: "Jerusalem, Israel",
      journey: "Early Church",
      lat: 31.7750,
      lng: 35.2300,
      chapters: [
        {
          title: "The Ascension — Waiting for the Promise",
          summary: "Before the story of the church began, Jesus appeared to his disciples over forty days after the resurrection — eating with them, speaking about the kingdom of God, and giving final instructions. He told them to wait in Jerusalem for the Holy Spirit, the promise of the Father. When they asked if this was the moment he would restore the kingdom to Israel, he redirected their attention: the times were not theirs to know. Their calling was to be witnesses — beginning in Jerusalem, then Judea, then Samaria, then to the ends of the earth. Then, as they watched, he was taken up into a cloud. Two angels appeared: why were they gazing into the sky? He would come back the same way they saw him go. The disciples returned to Jerusalem — not scattered, not in despair — and gathered in the upper room to pray.",
          kjvText: "And, being assembled together with them, commanded them that they should not depart from Jerusalem, but wait for the promise of the Father, which, saith he, ye have heard of me. For John truly baptized with water; but ye shall be baptized with the Holy Ghost not many days hence. When they therefore were come together, they asked of him, saying, Lord, wilt thou at this time restore again the kingdom to Israel? And he said unto them, It is not for you to know the times or the seasons, which the Father hath put in his own power. But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth. And when he had spoken these things, while they beheld, he was taken up; and a cloud received him out of their sight. And while they looked stedfastly toward heaven as he went up, behold, two men stood by them in white apparel; Which also said, Ye men of Galilee, why stand ye gazing up into heaven? this same Jesus, which is taken up from you into heaven, shall so come in like manner as ye have seen him go into heaven. Then returned they unto Jerusalem from the mount called Olivet, which is from Jerusalem a sabbath day's journey. And when they were come in, they went up into an upper room, where abode both Peter, and James, and John, and Andrew, Philip, and Thomas, Bartholomew, and Matthew, James the son of Alphaeus, and Simon Zelotes, and Judas the brother of James. These all continued with one accord in prayer and supplication, with the women, and Mary the mother of Jesus, and with his brethren.",
          kjvRef: "Acts 1:4–14",
          scriptureRef: "Acts 1:1–26",
          approximateDate: "early 30s AD",
          youtubeUrls: ["https://www.youtube.com/watch?v=QFLHNYZ-an4"]
        },
        {
          title: "Pentecost — The Church is Born",
          summary: "On the day of Pentecost, the believers were gathered in one place and suddenly a sound like a rushing wind filled the entire house, tongues of fire came to rest on each of them, and all were filled with the Holy Spirit. Peter stood to preach with great boldness, and about three thousand people accepted his message and were baptized that day. The movement of the church was marked from the beginning by the powerful coming of the Holy Spirit, not by human planning.",
          kjvText: "And when the day of Pentecost was fully come, they were all with one accord in one place. And suddenly there came a sound from heaven as of a rushing mighty wind, and it filled all the house where they were sitting. And there appeared unto them cloven tongues like as of fire, and it sat upon each of them. And they were all filled with the Holy Ghost, and began to speak with other tongues, as the Spirit gave them utterance.",
          kjvRef: "Acts 2:1–4",
          scriptureRef: "Acts 2:1–41",
          approximateDate: "early 30s AD",
          youtubeUrls: ["https://youtu.be/lBXWl0DWkZM?si=iEh9eFX3_UbUGQph"]
        },
        {
          title: "Signs, Boldness, and Holy Fear",
          summary: "Peter and John healed a man lame from birth at the temple gate, not by their own power but in the name of Jesus Christ. Peter preached that Jesus, crucified and risen, was the promised Messiah, and called Israel to repent. The apostles were arrested for preaching the resurrection, but Peter declared there was salvation in no one else. The believers prayed for boldness, and the Holy Spirit strengthened their witness. The church was marked by unity and radical generosity, with no one in need. God also brought holy fear through the judgment of Ananias and Sapphira for lying to the Holy Spirit. The council had the apostles flogged and ordered them to stop speaking in the name of Jesus — and they left rejoicing that they were counted worthy to suffer for his name. Despite opposition, the word of God continued to spread with power.",
          kjvText: "And they continued stedfastly in the apostles' doctrine and fellowship, and in breaking of bread, and in prayers. And fear came upon every soul: and many wonders and signs were done by the apostles. And all that believed were together, and had all things common.",
          kjvRef: "Acts 2:42–44",
          scriptureRef: "Acts 3–5",
          approximateDate: "early 30s AD",
          youtubeUrls: [
            "https://www.youtube.com/watch?v=UcXXhmFt_aw",
            "https://www.youtube.com/watch?v=z-tMnLNEIhM",
            "https://www.youtube.com/watch?v=RdzXNAPKCFQ"
          ]
        },
        {
          title: "Stephen's Martyrdom — The First Death",
          summary: "Stephen, one of the Seven chosen to serve the Jerusalem community, was full of faith and power, and performed signs and preached with such wisdom that the religious leaders could not answer him. They brought false charges, and as he stood before the council, his face shone like an angel's. He preached the full sweep of Israel's history, accusing them of always resisting the Holy Spirit. As stones fell on him, he saw Jesus standing at the right hand of God — and forgave his killers. Among those watching and approving: a young man named Saul.",
          kjvText: "And he kneeled down, and cried with a loud voice, Lord, lay not this sin to their charge. And when he had said this, he fell asleep. And Saul was consenting unto his death.",
          kjvRef: "Acts 7:60–8:1",
          scriptureRef: "Acts 6–7",
          approximateDate: "early–mid 30s AD",
          youtubeUrls: ["https://www.youtube.com/watch?v=0LjsilSxhlI&t=2s"]
        }
      ]
    },
    {
      id: 4,
      section: "acts",
      sequence: 4,
      type: "narrative",
      name: "Samaria",
      modernName: "West Bank region, Palestinian Territory",
      journey: "Philip's Ministry",
      lat: 32.2667,
      lng: 35.2000,
      title: "Philip in Samaria",
      summary: "Persecution scattered the Jerusalem church — with Saul among its chief instigators, entering homes and dragging believers to prison. But this only spread the gospel further. Philip went to the city of Samaria — a region Jews had despised for generations — and proclaimed Christ with such power that the city experienced great joy. Unclean spirits were cast out, and the paralyzed and lame were healed. Many in the city, who had previously been amazed by Simon the sorcerer — a man who claimed to be 'some great one' — turned to Christ in faith. Even Simon himself believed and was baptized. But when Peter and John came from Jerusalem and laid hands on the new believers, praying for them to receive the Holy Spirit, Simon offered them money for the power to give the Spirit. Peter rebuked him sharply — the gift of God was not for purchase. The Spirit that came upon these Samaritans was the same Spirit who had fallen at Pentecost, and the long-standing wall between Jew and Samaritan began to break.",
      kjvText: "Then Philip went down to the city of Samaria, and preached Christ unto them. And the people with one accord gave heed unto those things which Philip spake, hearing and seeing the miracles which he did. And there was great joy in that city.",
      kjvRef: "Acts 8:5–8",
      scriptureRef: "Acts 8:1–25",
      approximateDate: "mid–late 30s AD"
    },
    {
      id: 5,
      section: "acts",
      sequence: 5,
      type: "narrative",
      name: "Road to Gaza",
      modernName: "Southern Israel / Gaza region",
      journey: "Philip's Ministry",
      lat: 31.5000,
      lng: 34.7000,
      title: "The Ethiopian Eunuch",
      summary: "An angel sent Philip south onto a desert road toward Gaza. There he found a high official of the Ethiopian queen, sitting in his chariot reading aloud from Isaiah — the passage about the suffering servant. Philip ran alongside, asked if he understood what he was reading, and was invited in. He explained that Isaiah was speaking of Jesus. Before they traveled far, they came to water by the road, and the Ethiopian asked: what was stopping him from being baptized? The Ethiopian confessed faith in Christ, was baptized, and went on his way rejoicing.",
      kjvText: "And he answered and said, I believe that Jesus Christ is the Son of God. And he commanded the chariot to stand still: and they went down both into the water, both Philip and the eunuch; and he baptized him.",
      kjvRef: "Acts 8:37–38",
      scriptureRef: "Acts 8:26–40",
      approximateDate: "mid–late 30s AD"
    },
    {
      id: 6,
      section: "acts",
      sequence: 6,
      type: "narrative",
      name: "Damascus",
      modernName: "Damascus, Syria",
      journey: "Saul's Conversion",
      lat: 33.5138,
      lng: 36.2765,
      title: "Saul's Conversion",
      summary: "Saul of Tarsus — brilliant, zealous, and violently opposed to Christians — received letters authorizing him to arrest followers of the Way in Damascus and bring them bound to Jerusalem. On the road, a light from heaven suddenly blinded him, and a voice said: 'Saul, Saul, why do you persecute me?' The risen Jesus revealed himself as the one Saul had been opposing in his persecution of the church. Saul arrived in Damascus blind, fasting, and waiting for further instruction. After three days, a disciple named Ananias — sent by God despite his fear — came to him, called him 'brother Saul,' and laid hands on him so that his sight was restored. Saul was baptized and immediately began proclaiming Jesus in the synagogues, declaring him to be the Son of God and confounding those who heard him.",
      kjvText: "And Saul arose from the earth; and when his eyes were opened, he saw no man: but they led him by the hand, and brought him into Damascus. And he was three days without sight, and neither did eat nor drink.",
      kjvRef: "Acts 9:8–9",
      scriptureRef: "Acts 9:1–22",
      approximateDate: "mid–late 30s AD"
    },
    {
      id: 7,
      section: "acts",
      sequence: 7,
      type: "narrative",
      name: "Joppa",
      modernName: "Jaffa, Tel Aviv, Israel",
      journey: "Peter's Ministry",
      lat: 32.0549,
      lng: 34.7506,
      title: "Peter's Vision Begins",
      summary: "Peter was staying in Joppa at the house of Simon the tanner — already a culturally unusual choice — when he went up to the rooftop to pray around midday. He saw a vision of a sheet descending from heaven filled with animals considered unclean under Jewish law, and heard a voice: 'Rise, Peter; kill and eat.' He refused, and the voice came again, repeating the command. Each time Peter resisted, the response came: 'What God has cleansed, do not call common.' He did not yet understand what the vision meant. Meanwhile, messengers from Caesarea were arriving at the house.",
      kjvText: "And he became very hungry, and would have eaten: but while they made ready, he fell into a trance, And saw heaven opened, and a certain vessel descending upon him, as it had been a great sheet knit at the four corners, and let down to the earth.",
      kjvRef: "Acts 10:10–11",
      scriptureRef: "Acts 10:1–23",
      approximateDate: "late 30s to early 40s AD"
    },
    {
      id: 8,
      section: "acts",
      sequence: 8,
      type: "narrative",
      name: "Caesarea",
      modernName: "Caesarea, Israel",
      journey: "Peter's Ministry",
      lat: 32.5026,
      lng: 34.8940,
      title: "Cornelius — Gentiles Receive the Spirit",
      summary: "Cornelius was a Roman centurion — devout, generous, and praying — who received a vision directing him to send for Peter. When Peter arrived and began to speak, the Holy Spirit fell on Cornelius and his household just as he had fallen on the believers at Pentecost. Peter and the Jewish believers with him were astonished. The proof was undeniable: God had given the same gift to the Gentiles. Peter ordered them to be baptized. The gospel had crossed the deepest social wall of the ancient world.",
      kjvText: "While Peter yet spake these words, the Holy Ghost fell on all them which heard the word. And they of the circumcision which believed were astonished, as many as came with Peter, because that on the Gentiles also was poured out the gift of the Holy Ghost.",
      kjvRef: "Acts 10:44–45",
      scriptureRef: "Acts 10:24–48",
      approximateDate: "late 30s to early 40s AD"
    },
    {
      id: 9,
      section: "acts",
      sequence: 9,
      type: "narrative",
      name: "Antioch",
      modernName: "Antakya, Turkey",
      journey: "The Church at Antioch",
      lat: 36.2021,
      lng: 36.1604,
      chapters: [
        {
          title: "First Called Christians",
          summary: "Scattered believers reached Antioch — a great cosmopolitan city of the Roman world — and began preaching to Greeks as well as Jews. The church that formed there was a significantly Gentile congregation. Barnabas was sent from Jerusalem to investigate and immediately recognized God's grace at work. He traveled to find Saul in Tarsus and brought him to Antioch, where they taught together for a full year. It was there, in this unlikely city, that disciples were first called 'Christians.'",
          kjvText: "And the disciples were called Christians first in Antioch.",
          kjvRef: "Acts 11:26",
          scriptureRef: "Acts 11:19–26",
          approximateDate: "~AD 40–45"
        },
        {
          title: "Commissioned and Sent — First Journey Begins",
          summary: "As the church in Antioch worshipped and fasted, the Holy Spirit spoke: 'Set apart for me Barnabas and Saul for the work to which I have called them.' After fasting and prayer, the church laid hands on them and sent them out. This was the beginning of the first deliberate, church-commissioned missionary journey. Paul and Barnabas set out not in their own strength but sent by both the Spirit and the community.",
          kjvText: "As they ministered to the Lord, and fasted, the Holy Ghost said, Separate me Barnabas and Saul for the work whereunto I have called them. And when they had fasted and prayed, and laid their hands on them, they sent them away.",
          kjvRef: "Acts 13:2–3",
          scriptureRef: "Acts 13:1–3",
          approximateDate: "~AD 46–49"
        }
      ]
    },
    {
      id: 11,
      section: "acts",
      sequence: 11,
      type: "narrative",
      name: "Cyprus",
      modernName: "Cyprus (Salamis to Paphos)",
      journey: "Paul's First Missionary Journey",
      lat: 34.9208,
      lng: 33.6230,
      title: "Sergius Paulus — The Proconsul Believes",
      summary: "Paul and Barnabas sailed to Cyprus — Barnabas's home island — and traveled the length of it preaching in synagogues. At Paphos, the Roman proconsul Sergius Paulus sent for them, genuinely wanting to hear the word of God. But a sorcerer named Elymas tried to interfere. Paul, filled with the Spirit, pronounced blindness on him — and when the proconsul saw it happen, he believed. A Roman official of significant power became a follower of Christ. It was also here that Saul began consistently using the name Paul.",
      kjvText: "Then the deputy, when he saw what was done, believed, being astonished at the doctrine of the Lord.",
      kjvRef: "Acts 13:12",
      scriptureRef: "Acts 13:4–12",
      approximateDate: "~46 AD"
    },
    {
      id: 12,
      section: "acts",
      sequence: 12,
      type: "narrative",
      name: "Perga",
      modernName: "Murtina / near Antalya, Turkey",
      journey: "Paul's First Missionary Journey",
      lat: 36.9600,
      lng: 30.8500,
      title: "John Mark Departs",
      summary: "Paul and Barnabas arrived in Perga in Pamphylia — the southern coast of modern Turkey. There John Mark, who had come with them as an assistant, left and returned to Jerusalem. The text gives no explanation. Later, this moment would cause a painful split between Paul and Barnabas. Paul considered the departure a desertion; Barnabas wanted to give Mark another chance. Whatever the reason, Paul and Barnabas pressed on northward into the rugged Anatolian highlands.",
      kjvText: "And John departing from them returned to Jerusalem.",
      kjvRef: "Acts 13:13",
      scriptureRef: "Acts 13:13",
      approximateDate: "~46 AD"
    },
    {
      id: 13,
      section: "acts",
      sequence: 13,
      type: "narrative",
      name: "Pisidian Antioch",
      modernName: "Yalvaç, Turkey",
      journey: "Paul's First Missionary Journey",
      lat: 38.2992,
      lng: 31.1883,
      title: "Synagogue Sermon — To the Jew First",
      summary: "Paul preached one of his most complete recorded sermons in the synagogue of Pisidian Antioch — tracing God's faithfulness from Egypt through David to the resurrection of Jesus. The response was remarkable: the next Sabbath, nearly the whole city came to hear. But the Jewish leaders, filled with jealousy, contradicted and blasphemed. Paul turned to them and made a declaration that would echo through the rest of his ministry: 'Since you thrust the word of God from you, we turn to the Gentiles.'",
      kjvText: "Then Paul and Barnabas waxed bold, and said, It was necessary that the word of God should first have been spoken to you: but seeing ye put it from you, and judge yourselves unworthy of everlasting life, lo, we turn to the Gentiles.",
      kjvRef: "Acts 13:46",
      scriptureRef: "Acts 13:14–52",
      approximateDate: "~AD 46–49"
    },
    {
      id: 14,
      section: "acts",
      sequence: 14,
      type: "narrative",
      name: "Iconium",
      modernName: "Konya, Turkey",
      journey: "Paul's First Missionary Journey",
      lat: 37.8715,
      lng: 32.4846,
      title: "Divided City",
      summary: "In Iconium, Paul and Barnabas spoke with such power in the synagogue that a great multitude of both Jews and Greeks believed. But the city became divided — some with the Jews, some with the apostles. Plots were formed to stone them. Paul and Barnabas stayed long enough to make many disciples, performing signs and wonders, before they learned of a conspiracy against them and moved on. Opposition did not end the mission; it redirected it.",
      kjvText: "Long time therefore abode they speaking boldly in the Lord, which gave testimony unto the word of his grace, and granted signs and wonders to be done by their hands.",
      kjvRef: "Acts 14:3",
      scriptureRef: "Acts 14:1–7",
      approximateDate: "~AD 46–49"
    },
    {
      id: 15,
      section: "acts",
      sequence: 15,
      type: "narrative",
      name: "Lystra",
      modernName: "Near Hatunsaray, Turkey",
      journey: "Paul's First Missionary Journey",
      lat: 37.5700,
      lng: 32.4000,
      title: "Paul Stoned — Left for Dead",
      summary: "In Lystra, Paul healed a man lame from birth, and the crowd erupted, calling Barnabas Zeus and Paul Hermes — preparing to offer sacrifices to them. Paul and Barnabas tore their clothes in horror and barely restrained the crowd. Then Jews from Antioch and Iconium arrived, turned the crowd against them, and Paul was stoned and dragged outside the city, left for dead. He got up. He walked back into the city. The next day he continued to Derbe. He was the man who later wrote that he had learned, in whatever state he was, to be content.",
      kjvText: "And there came thither certain Jews from Antioch and Iconium, who persuaded the people, and, having stoned Paul, drew him out of the city, supposing he had been dead. Howbeit, as the disciples stood round about him, he rose up, and came into the city.",
      kjvRef: "Acts 14:19–20",
      scriptureRef: "Acts 14:8–20",
      approximateDate: "~AD 46–49"
    },
    {
      id: 16,
      section: "acts",
      sequence: 16,
      type: "narrative",
      name: "Derbe",
      modernName: "Near Kerti Höyük, Turkey",
      journey: "Paul's First Missionary Journey",
      lat: 37.3500,
      lng: 33.4000,
      title: "Many Disciples",
      summary: "Derbe was the furthest east Paul reached on this journey — and the text is quiet about it. No riots, no miracles recorded, no drama. They preached the gospel, made many disciples, and that was enough. Derbe may be the most underappreciated stop of the first journey: a town where people simply believed. From there, rather than continuing east toward home, Paul and Barnabas retraced their steps through hostile territory to strengthen the new churches.",
      kjvText: "And when they had preached the gospel to that city, and had taught many, they returned again to Lystra, and to Iconium, and Antioch.",
      kjvRef: "Acts 14:21",
      scriptureRef: "Acts 14:20–21",
      approximateDate: "~AD 46–49"
    },
    {
      id: 17,
      section: "acts",
      sequence: 17,
      type: "narrative",
      name: "Antioch",
      modernName: "Antakya, Turkey",
      journey: "Paul's First Missionary Journey",
      lat: 36.2021,
      lng: 36.1604,
      title: "Return — Report to the Church",
      summary: "Paul and Barnabas returned to Antioch — the church that had sent them — and gathered the congregation to report what God had done. The first missionary journey was complete. They had planted churches across southern Turkey, been thrown out of cities, stoned, worshipped as gods, and made disciples in every place they visited. Their report carried one particular note of wonder: God had opened a door of faith to the Gentiles. The church in Antioch rejoiced.",
      kjvText: "And thence sailed to Antioch, from whence they had been recommended to the grace of God for the work which they fulfilled. And when they were come, and had gathered the church together, they rehearsed all that God had done with them, and how he had opened the door of faith unto the Gentiles.",
      kjvRef: "Acts 14:26–27",
      scriptureRef: "Acts 14:21–28",
      approximateDate: "~AD 46–49"
    },
    {
      id: 18,
      section: "acts",
      sequence: 18,
      type: "narrative",
      name: "Jerusalem",
      modernName: "Jerusalem, Israel",
      journey: "Jerusalem Council",
      lat: 31.7683,
      lng: 35.2137,
      title: "Jerusalem Council — Gentiles and the Law",
      summary: "A crisis arose: some teachers from Judea had been telling Gentile believers they must be circumcised and keep the law of Moses to be saved. Paul and Barnabas went to Jerusalem to settle the question with the apostles and elders. After intense debate, Peter stood — invoking his own experience with Cornelius — and declared that God had made no distinction between Jew and Gentile, purifying both hearts by faith. James the brother of Jesus gave the ruling: do not burden the Gentiles. A letter was sent. The gospel remained free.",
      kjvText: "Now therefore why tempt ye God, to put a yoke upon the neck of the disciples, which neither our fathers nor we were able to bear? But we believe that through the grace of the Lord Jesus Christ we shall be saved, even as they.",
      kjvRef: "Acts 15:10–11",
      scriptureRef: "Acts 15:1–29",
      approximateDate: "~AD 48–50"
    },
    {
      id: 19,
      section: "acts",
      sequence: 19,
      type: "narrative",
      name: "Antioch",
      modernName: "Antakya, Turkey",
      journey: "Paul's Second Missionary Journey",
      lat: 36.2021,
      lng: 36.1604,
      title: "Barnabas and Paul Part Ways",
      summary: "Paul proposed returning to visit every city where they had preached on the first journey. Barnabas wanted to take John Mark along again. Paul refused — Mark had abandoned them in Pamphylia. The disagreement was sharp enough to end their partnership. Barnabas took Mark to Cyprus; Paul chose Silas and headed overland. Two mission teams formed from what had been one. Paul's later letters show that both Mark and Barnabas were eventually restored in his estimation — but for now, they went separate ways.",
      kjvText: "And the contention was so sharp between them, that they departed asunder one from the other: and so Barnabas took Mark, and sailed unto Cyprus; And Paul chose Silas, and departed, being recommended by the brethren unto the grace of God.",
      kjvRef: "Acts 15:39–40",
      scriptureRef: "Acts 15:36–41",
      approximateDate: "~AD 48–50"
    },
    {
      id: 20,
      section: "acts",
      sequence: 20,
      type: "narrative",
      name: "Lystra",
      modernName: "Near Hatunsaray, Turkey",
      journey: "Paul's Second Missionary Journey",
      lat: 37.5700,
      lng: 32.4000,
      title: "Timothy Joins",
      summary: "Paul returned to Lystra — where he had been stoned on the first journey — and found a young disciple named Timothy, well-spoken of by believers in Lystra and Iconium, the son of a Jewish mother and Greek father. Paul wanted to take him along. He had Timothy circumcised — not as a requirement for salvation, but to prevent the mission to Jews from being blocked on cultural grounds. Timothy would become Paul's most trusted companion, partner, and 'true son in the faith.'",
      kjvText: "Him would Paul have to go forth with him; and took and circumcised him because of the Jews which were in those quarters: for they knew all that his father was a Greek.",
      kjvRef: "Acts 16:3",
      scriptureRef: "Acts 16:1–5",
      approximateDate: "~AD 49–53"
    },
    {
      id: 21,
      section: "acts",
      sequence: 21,
      type: "narrative",
      name: "Troas",
      modernName: "Near Dalyan / Alexandria Troas, Turkey",
      journey: "Paul's Second Missionary Journey",
      lat: 39.7500,
      lng: 26.1667,
      title: "The Macedonian Vision",
      summary: "Paul, Silas, and Timothy had been blocked from going into Asia and Bithynia — the Spirit would not allow it, though the text gives no explanation. They found themselves at Troas on the Aegean coast, with nowhere obvious to go. That night, Paul saw a vision: a man of Macedonia standing and pleading — 'Come over and help us.' They concluded immediately that God was calling them westward. They sailed at dawn. The gospel was about to enter Europe for the first time.",
      kjvText: "And a vision appeared to Paul in the night; There stood a man of Macedonia, and prayed him, saying, Come over into Macedonia, and help us. And after he had seen the vision, immediately we endeavoured to go into Macedonia, assuredly gathering that the Lord had called us for to preach the gospel unto them.",
      kjvRef: "Acts 16:9–10",
      scriptureRef: "Acts 16:6–10",
      approximateDate: "~AD 49–53"
    },
    {
      id: 22,
      section: "acts",
      sequence: 22,
      type: "narrative",
      name: "Philippi",
      modernName: "Near Kavala, Greece",
      journey: "Paul's Second Missionary Journey",
      lat: 41.0137,
      lng: 24.2875,
      title: "Lydia, Prison, Earthquake",
      summary: "Philippi was a Roman colony — proud, military, Latin-speaking. Paul found no synagogue, only a prayer gathering by the river where he met Lydia, a dealer in purple cloth from Thyatira. She and her household became the first recorded converts in the region. Later, a slave girl with a spirit of divination followed them for days until Paul cast out the spirit — which destroyed her owners' income. Paul and Silas were beaten and thrown into prison. At midnight they were singing hymns. An earthquake opened every door and loosed every chain. The jailer, trembling, asked: 'What must I do to be saved?'",
      kjvText: "And at midnight Paul and Silas prayed, and sang praises unto God: and the prisoners heard them. And suddenly there was a great earthquake, so that the foundations of the prison were shaken: and immediately all the doors were opened, and every one's bands were loosed.",
      kjvRef: "Acts 16:25–26",
      scriptureRef: "Acts 16:11–40",
      approximateDate: "~AD 49–53"
    },
    {
      id: 23,
      section: "acts",
      sequence: 23,
      type: "narrative",
      name: "Thessalonica",
      modernName: "Thessaloniki, Greece",
      journey: "Paul's Second Missionary Journey",
      lat: 40.6401,
      lng: 22.9444,
      title: "These Who Have Turned the World Upside Down",
      summary: "Paul reasoned in the synagogue for three Sabbaths, explaining that the Messiah had to suffer and rise from the dead. Some Jews believed; a great multitude of devout Greeks and a number of leading women believed. But jealous Jews gathered a mob, dragging the homeowner Jason before city officials and accusing: 'These who have turned the world upside down have come here also.' The charge was meant as an accusation. History reads it as an epitaph.",
      kjvText: "And Jason hath received them: and these all do contrary to the decrees of Caesar, saying that there is another king, one Jesus.",
      kjvRef: "Acts 17:7",
      scriptureRef: "Acts 17:1–9",
      approximateDate: "~AD 49–53"
    },
    {
      id: 24,
      section: "acts",
      sequence: 24,
      type: "narrative",
      name: "Berea",
      modernName: "Veria, Greece",
      journey: "Paul's Second Missionary Journey",
      lat: 40.5236,
      lng: 22.2044,
      title: "The Noble Bereans",
      summary: "Paul arrived in Berea and found something rare — Jews who received the word with readiness and searched the Scriptures daily to verify whether the things Paul was saying were true. Many believed, including Greek women of high standing. The Bereans are remembered not for dramatic miracles or great suffering but for diligence: they checked. When Paul's enemies from Thessalonica arrived to stir up trouble, believers escorted Paul out of town. Silas and Timothy stayed behind to strengthen the new church.",
      kjvText: "These were more noble than those in Thessalonica, in that they received the word with all readiness of mind, and searched the scriptures daily, whether those things were so.",
      kjvRef: "Acts 17:11",
      scriptureRef: "Acts 17:10–15",
      approximateDate: "~AD 49–53"
    },
    {
      id: 25,
      section: "acts",
      sequence: 25,
      type: "narrative",
      name: "Athens",
      modernName: "Athens, Greece",
      journey: "Paul's Second Missionary Journey",
      lat: 37.9838,
      lng: 23.7275,
      title: "Mars Hill — The Unknown God",
      summary: "Paul waited in Athens and his spirit was provoked by the city full of idols. He reasoned daily in the synagogue and in the marketplace. Epicurean and Stoic philosophers took him to the Areopagus — Mars Hill — to hear this strange new teaching. He began not with Scripture but with what they already knew: the altar inscribed 'TO AN UNKNOWN GOD.' He declared: the God who made the world does not live in temples made with hands. God had fixed a day on which he would judge the world by the man he had raised from the dead. Some sneered. Some said they would hear him again. A few believed.",
      kjvText: "For as I passed by, and beheld your devotions, I found an altar with this inscription, TO THE UNKNOWN GOD. Whom therefore ye ignorantly worship, him declare I unto you.",
      kjvRef: "Acts 17:23",
      scriptureRef: "Acts 17:16–34",
      approximateDate: "~AD 49–53"
    },
    {
      id: 26,
      section: "acts",
      sequence: 26,
      type: "narrative",
      name: "Corinth",
      modernName: "Corinth, Greece",
      journey: "Paul's Second Missionary Journey",
      lat: 37.9387,
      lng: 22.9283,
      title: "Eighteen Months in Corinth",
      summary: "Corinth was wealthy, cosmopolitan, and notorious for immorality — a crossroads port city with temples and vice in abundance. Paul arrived and by his own account came 'in weakness and in fear.' He found Aquila and Priscilla — tentmakers expelled from Rome — and worked alongside them by trade while preaching every Sabbath. When opposition intensified, God spoke to Paul in a vision: 'Do not be silent, for I am with you.' He stayed eighteen months. The church he planted there was large, gifted, and troubled. He later wrote them two letters.",
      kjvText: "And the Lord said to Paul in the night by a vision, Be not afraid, but speak, and hold not thy peace: For I am with thee, and no man shall set on thee to hurt thee: for I have much people in this city.",
      kjvRef: "Acts 18:9–10",
      scriptureRef: "Acts 18:1–18",
      approximateDate: "~AD 50–52 (Gallio inscription)"
    },
    {
      id: 27,
      section: "acts",
      sequence: 27,
      type: "narrative",
      name: "Ephesus",
      modernName: "Selçuk (near Ephesus), Turkey",
      journey: "Paul's Second Missionary Journey",
      lat: 37.9395,
      lng: 27.3417,
      title: "Brief Visit — Promise to Return",
      summary: "Sailing east, Paul stopped briefly in Ephesus and reasoned with the Jews in the synagogue. They asked him to stay longer; he declined, promising to return if God willed. He left Aquila and Priscilla there. This brief visit planted a seed — Apollos arrived later and was instructed there by Priscilla and Aquila. When Paul returned on his third journey, Ephesus became the center of the most extended ministry of his career.",
      kjvText: "But he left them, and sailed from Ephesus: but bade them farewell, saying, I must by all means keep this feast that cometh in Jerusalem: but I will return again unto you, if God will.",
      kjvRef: "Acts 18:21",
      scriptureRef: "Acts 18:19–21",
      approximateDate: "~AD 52–53"
    },
    {
      id: 28,
      section: "acts",
      sequence: 28,
      type: "narrative",
      name: "Jerusalem",
      modernName: "Jerusalem, Israel",
      journey: "Paul's Second Missionary Journey",
      lat: 31.7683,
      lng: 35.2137,
      title: "Return Visit to Jerusalem",
      summary: "Paul returned to Jerusalem briefly — likely for the feast of Pentecost — before returning to Antioch. Luke's account of this visit is almost parenthetical: 'he went up and greeted the church, and then went down to Antioch.' The second journey was complete: launched from Antioch, through Turkey, into Europe for the first time, then back. The churches in Macedonia and Achaia had been planted. Paul would not return to Jerusalem again until the end of his third journey — when he would not leave as a free man.",
      kjvText: "And he said farewell to them, saying, I must by all means keep this feast that cometh in Jerusalem: but I will return again unto you, if God will.",
      kjvRef: "Acts 18:21",
      scriptureRef: "Acts 18:22",
      approximateDate: "~AD 52–53"
    },
    {
      id: 29,
      section: "acts",
      sequence: 29,
      type: "narrative",
      name: "Ephesus",
      modernName: "Selçuk (near Ephesus), Turkey",
      journey: "Paul's Third Missionary Journey",
      lat: 37.9395,
      lng: 27.3417,
      title: "Three Years in Ephesus — School of Tyrannus",
      summary: "Paul returned to Ephesus and stayed for nearly three years — the longest recorded stay in any city. He began in the synagogue, then moved his teaching to the lecture hall of Tyrannus, teaching daily for two years. All who lived in the province of Asia heard the word. Handkerchiefs and aprons from Paul's hands brought healing. Exorcists attempted to use Jesus's name without faith — and were beaten by the demonized man, fleeing naked. Sorcerers burned their books publicly. Finally, the silversmiths who made shrines of Artemis rioted because the gospel was destroying their trade.",
      kjvText: "And this continued by the space of two years; so that all they which dwelt in Asia heard the word of the Lord Jesus, both Jews and Greeks.",
      kjvRef: "Acts 19:10",
      scriptureRef: "Acts 19:1–41",
      approximateDate: "~AD 52–57"
    },
    {
      id: 30,
      section: "acts",
      sequence: 30,
      type: "narrative",
      name: "Macedonia and Greece",
      modernName: "Greece / North Macedonia region",
      journey: "Paul's Third Missionary Journey",
      lat: 40.9000,
      lng: 23.0000,
      title: "Strengthening the Churches",
      summary: "Paul traveled through Macedonia — revisiting Philippi, Thessalonica, Berea — encouraging and strengthening the churches he had planted on the second journey. He spent three months in Greece, likely in Corinth. A plot against him by Jews caused him to change his plans and travel overland back north rather than sail directly. He gathered around him a team of representatives from the churches who would accompany him to Jerusalem: Sopater, Aristarchus, Secundus, Gaius, Timothy, Tychicus, and Trophimus.",
      kjvText: "And he went over those parts, and had given them much exhortation, he came into Greece, And there abode three months.",
      kjvRef: "Acts 20:2–3",
      scriptureRef: "Acts 20:1–6",
      approximateDate: "~AD 53–57"
    },
    {
      id: 31,
      section: "acts",
      sequence: 31,
      type: "narrative",
      name: "Troas",
      modernName: "Near Dalyan / Alexandria Troas, Turkey",
      journey: "Paul's Third Missionary Journey",
      lat: 39.7500,
      lng: 26.1667,
      title: "Eutychus Raised to Life",
      summary: "In Troas, Paul met with believers on the first day of the week to break bread. He preached until midnight — he was leaving the next day — and a young man named Eutychus, sitting in the window on the third floor, sank into deep sleep and fell to his death. Paul went down, embraced him, and announced that his life was still in him. They went back upstairs, broke bread, and Paul continued talking until dawn. Luke records that they brought the young man home alive, and the community was 'not a little comforted' — meaning grief gave way to overwhelming joy.",
      kjvText: "And there were many lights in the upper chamber, where they were gathered together. And there sat in a window a certain young man named Eutychus, being fallen into a deep sleep: and as Paul was long preaching, he sunk down with sleep, and fell down from the third loft, and was taken up dead.",
      kjvRef: "Acts 20:8–9",
      scriptureRef: "Acts 20:7–12",
      approximateDate: "~AD 57"
    },
    {
      id: 32,
      section: "acts",
      sequence: 32,
      type: "narrative",
      name: "Miletus",
      modernName: "Near Akköy, Turkey",
      journey: "Paul's Third Missionary Journey",
      lat: 37.5285,
      lng: 27.2764,
      title: "Farewell to the Ephesian Elders",
      summary: "Paul sent to Ephesus for the elders of the church — he would not go there himself, pressing to reach Jerusalem by Pentecost. When they arrived, he gave what was in effect his last pastoral address to the church he loved most. He recounted his ministry among them: how he had served with tears, taught them publicly and house to house, warned them night and day. He told them he was bound to Jerusalem, not knowing what would befall him — only that the Spirit bore witness that chains and afflictions awaited. He would never see them again. They all knelt on the beach and wept.",
      kjvText: "And now, behold, I know that ye all, among whom I have gone preaching the kingdom of God, shall see my face no more. Wherefore I take you to record this day, that I am pure from the blood of all men.",
      kjvRef: "Acts 20:25–26",
      scriptureRef: "Acts 20:13–38",
      approximateDate: "~AD 57"
    },
    {
      id: 33,
      section: "acts",
      sequence: 33,
      type: "narrative",
      name: "Caesarea",
      modernName: "Caesarea, Israel",
      journey: "Paul's Third Missionary Journey",
      lat: 32.5026,
      lng: 34.8940,
      title: "Agabus Prophecy — 'So Shall the Jews Bind This Man'",
      summary: "Paul arrived at Caesarea and stayed with Philip the evangelist — one of the Seven, whose daughters prophesied. A prophet named Agabus came down from Judea, took Paul's belt, bound his own hands and feet, and declared: 'Thus saith the Holy Ghost, So shall the Jews at Jerusalem bind the man that owneth this girdle.' The people begged Paul not to go. He answered: I am ready not only to be bound, but to die at Jerusalem for the name of the Lord Jesus. And when they could not persuade him, they ceased — saying: the will of the Lord be done.",
      kjvText: "And when he would not be persuaded, we ceased, saying, The will of the Lord be done.",
      kjvRef: "Acts 21:14",
      scriptureRef: "Acts 21:8–14",
      approximateDate: "~AD 57"
    },
    {
      id: 34,
      section: "acts",
      sequence: 34,
      type: "narrative",
      name: "Jerusalem",
      modernName: "Jerusalem, Israel",
      journey: "Paul's Arrest & Trials",
      lat: 31.7683,
      lng: 35.2137,
      chapters: [
        {
          title: "Arrest in the Temple",
          summary: "Paul's arrival in Jerusalem seemed promising — he met with James, reported what God had done among the Gentiles, and was received gladly. But Jews from Asia recognized him in the temple and seized him, shouting that he had defiled the holy place by bringing a Gentile in. The whole city was stirred up. They were beating Paul to death when Roman soldiers rushed in and arrested him. As he was carried up the steps of the barracks, he asked permission to speak to the crowd. Standing there, chained, he began his defense — in Hebrew.",
          kjvText: "And as they went about to kill him, tidings came unto the chief captain of the band, that all Jerusalem was in an uproar. Who immediately took soldiers and centurions, and ran down unto them: and when they saw the chief captain and the soldiers, they left beating of Paul.",
          kjvRef: "Acts 21:31–32",
          scriptureRef: "Acts 21:15–36",
          approximateDate: "~AD 57"
        },
        {
          title: "Trials Before the Sanhedrin",
          summary: "Paul was brought before the Jewish council. He immediately identified himself as a Pharisee and declared the controversy was over the resurrection of the dead — splitting the council between Pharisees and Sadducees so completely that the Roman commander had to rescue him by force. That night the Lord stood beside Paul: 'Be of good cheer, Paul: for as thou hast testified of me in Jerusalem, so must thou bear witness also at Rome.' A plot of forty men swore an oath not to eat or drink until Paul was dead. He was transferred under heavy guard to Caesarea.",
          kjvText: "And the night following the Lord stood by him, and said, Be of good cheer, Paul: for as thou hast testified of me in Jerusalem, so must thou bear witness also at Rome.",
          kjvRef: "Acts 23:11",
          scriptureRef: "Acts 22–23",
          approximateDate: "~AD 57"
        }
      ]
    },
    {
      id: 36,
      section: "acts",
      sequence: 36,
      type: "narrative",
      name: "Caesarea",
      modernName: "Caesarea, Israel",
      journey: "Paul's Arrest & Trials",
      lat: 32.5026,
      lng: 34.8940,
      title: "Trials Before Felix, Festus, and Agrippa",
      summary: "Paul spent two years imprisoned in Caesarea under Felix, who hoped for a bribe. When Festus succeeded Felix, Paul exercised his right as a Roman citizen: 'I appeal to Caesar.' Agrippa the king came to hear him, and Paul delivered his defense with such force that Agrippa said: 'Almost thou persuadest me to be a Christian.' Paul replied that he wished Agrippa, and all who heard him, were as he was — except for the chains. Festus and Agrippa agreed: this man had done nothing worthy of death or imprisonment. But he had appealed to Caesar, and to Caesar he had to go.",
      kjvText: "Then Agrippa said unto Paul, Almost thou persuadest me to be a Christian. And Paul said, I would to God, that not only thou, but also all that hear me this day, were both almost, and altogether such as I am, except these bonds.",
      kjvRef: "Acts 26:28–29",
      scriptureRef: "Acts 24–26",
      approximateDate: "~AD 57–60 (Festus governorship)"
    },
    {
      id: 37,
      section: "acts",
      sequence: 37,
      type: "narrative",
      name: "Fair Havens, Crete",
      modernName: "Limenas Kalón Limenón, Crete, Greece",
      journey: "Journey to Rome",
      lat: 34.9200,
      lng: 24.9000,
      title: "Warning Ignored — Storm Ahead",
      summary: "Paul sailed for Rome as a prisoner. At Fair Havens on the southern coast of Crete, he urged the centurion: the sailing was dangerous, this voyage would end in disaster and great loss. He was not a sailor. He was not heeded. They sailed on. A fierce nor'easter caught them and for days they could not see sun or stars — all hope of being saved was abandoned. Then Paul stood among them and said: take courage. An angel had told him no life would be lost. Only the ship. He had appealed to Caesar; before Caesar they would stand.",
      kjvText: "But after long abstinence Paul stood forth in the midst of them, and said, Sirs, ye should have hearkened unto me, and not have loosed from Crete, and to have gained this harm and loss.",
      kjvRef: "Acts 27:21",
      scriptureRef: "Acts 27:8–26",
      approximateDate: "~AD 59–60"
    },
    {
      id: 38,
      section: "acts",
      sequence: 38,
      type: "narrative",
      name: "Malta",
      modernName: "Malta",
      journey: "Journey to Rome",
      lat: 35.9375,
      lng: 14.3754,
      title: "Shipwreck, Viper, Healings",
      summary: "After fourteen days adrift, the ship ran aground and broke apart on the coast of Malta. All 276 people on board reached shore safely — as Paul had declared. The local people showed them unusual kindness, building a fire in the rain and cold. A viper fastened on Paul's hand from the heat of the fire; the islanders watched for him to swell and die. He shook it into the fire and felt nothing. The father of the island's leading official was healed of fever and dysentery. The sick of the whole island came to Paul and were healed. They wintered in Malta for three months.",
      kjvText: "And when Paul had gathered a bundle of sticks, and laid them on the fire, there came a viper out of the heat, and fastened on his hand. And he shook off the beast into the fire, and felt no harm.",
      kjvRef: "Acts 28:3, 5",
      scriptureRef: "Acts 28:1–10",
      approximateDate: "~AD 59–60"
    },
    {
      id: 39,
      section: "acts",
      sequence: 39,
      type: "narrative",
      name: "Rome",
      modernName: "Rome, Italy",
      journey: "Journey to Rome",
      lat: 41.9028,
      lng: 12.4964,
      title: "Rome — Preaching Freely",
      summary: "Paul entered Rome. He had wanted to come there for years — had written the church there an entire letter full of theology. He arrived in chains, but the Lord had told him he would come. He was allowed to live by himself with the soldier who guarded him. He called the local Jewish leaders, explained his situation, and spent a whole day laying out the kingdom of God from Moses and the prophets. Some believed; some disbelieved. He stayed two full years, welcoming all who came, preaching the kingdom and teaching about the Lord Jesus Christ — openly and unhindered. That is where Luke's account ends. Not with a verdict. With the word unhindered.",
      kjvText: "And Paul dwelt two whole years in his own hired house, and received all that came in unto him, Preaching the kingdom of God, and teaching those things which concern the Lord Jesus Christ, with all confidence, no man forbidding him.",
      kjvRef: "Acts 28:30–31",
      scriptureRef: "Acts 28:11–31",
      approximateDate: "~AD 60–62"
    }
  ],

  jesus: [
    {
      id: 1,
      section: "jesus",
      sequence: 1,
      type: "narrative",
      name: "Bethlehem",
      modernName: "Bethlehem, West Bank",
      lat: 31.7054,
      lng: 35.2024,
      title: "The Birth of Jesus",
      summary: "Caesar Augustus issues a decree for a census, sending Joseph and his betrothed wife Mary from Nazareth to Bethlehem — the city of David, Joseph's ancestral home. There are no rooms. Jesus is born in a place where animals are kept, and laid in a feeding trough. Angels announce the birth to shepherds in nearby fields. Wise men come from the east, guided by a star. The eternal Word of God enters the world in poverty, in a small occupied town, born to parents of no political importance.",
      kjvText: "And she brought forth her firstborn son, and wrapped him in swaddling clothes, and laid him in a manger; because there was no room for them in the inn.",
      kjvRef: "Luke 2:7",
      scriptureRef: "Luke 2:1–20; Matthew 2:1–12",
      approximateDate: "~5–4 BC"
    },
    {
      id: 2,
      section: "jesus",
      sequence: 2,
      type: "narrative",
      name: "Nazareth",
      modernName: "Nazareth, Israel",
      lat: 32.7021,
      lng: 35.2977,
      title: "Childhood and Hidden Years",
      summary: "After the flight to Egypt and Herod's death, the family returns and settles in Nazareth of Galilee. This is where Jesus grows up — a small hill town in Galilee, looked down upon even by other Galileans. At twelve, he stays behind in Jerusalem after Passover, found in the temple courts questioning the teachers, who are astonished at his understanding. He returns to Nazareth and is subject to his parents. The next eighteen years of his life are not recorded. When he returns to Nazareth at the start of his ministry, the townspeople ask: 'Is this not the carpenter's son?'",
      kjvText: "And he went down with them, and came to Nazareth, and was subject unto them: but his mother kept all these sayings in her heart. And Jesus increased in wisdom and stature, and in favour with God and man.",
      kjvRef: "Luke 2:51–52",
      scriptureRef: "Matthew 2:19–23; Luke 2:39–52",
      approximateDate: "~4 BC – 27 AD"
    },
    {
      id: 3,
      section: "jesus",
      sequence: 3,
      type: "narrative",
      name: "Jordan River / Bethany Beyond Jordan",
      modernName: "Near Al-Maghtas, Jordan",
      lat: 31.8333,
      lng: 35.5500,
      title: "Baptism of Jesus",
      summary: "John the Baptist is preaching in the wilderness and baptizing in the Jordan — calling Israel to repentance. Jesus comes from Galilee to be baptized. John protests: I have need to be baptized of thee, and comest thou to me? Jesus insists. As he comes up from the water, the heavens open, the Spirit descends like a dove, and a voice from heaven declares: 'This is my beloved Son, in whom I am well pleased.' The ministry of Jesus begins not with a sign of power, but with identification with sinners and the Father's spoken approval.",
      kjvText: "And Jesus, when he was baptized, went up straightway out of the water: and, lo, the heavens were opened unto him, and he saw the Spirit of God descending like a dove, and lighting upon him: And lo a voice from heaven, saying, This is my beloved Son, in whom I am well pleased.",
      kjvRef: "Matthew 3:16–17",
      scriptureRef: "Matthew 3:13–17; Mark 1:9–11; Luke 3:21–22",
      approximateDate: "~27–28 AD"
    },
    {
      id: 4,
      section: "jesus",
      sequence: 4,
      type: "narrative",
      name: "Wilderness of Judea",
      modernName: "Judean Desert, West Bank / Israel",
      lat: 31.7000,
      lng: 35.3500,
      title: "Temptation in the Desert",
      summary: "The Spirit leads Jesus into the wilderness immediately after his baptism. For forty days he fasts, and the devil tempts him three times — to turn stones into bread, to leap from the temple and demand angelic rescue, to bow and receive all the kingdoms of the world. To each, Jesus answers with Scripture. He is hungry, he is alone, and he does not yield. When the testing is finished, angels come and minister to him. Where Adam failed in a garden, Jesus holds in a desert.",
      kjvText: "Then was Jesus led up of the Spirit into the wilderness to be tempted of the devil. And when he had fasted forty days and forty nights, he was afterward an hungred.",
      kjvRef: "Matthew 4:1–2",
      scriptureRef: "Matthew 4:1–11; Luke 4:1–13",
      approximateDate: "~27–28 AD"
    },
    {
      id: 5,
      section: "jesus",
      sequence: 5,
      type: "narrative",
      name: "Cana",
      modernName: "Kafr Kanna, Israel",
      lat: 32.7473,
      lng: 35.3490,
      title: "First Miracle — Water into Wine",
      summary: "Jesus attends a wedding in Cana with his mother and disciples. The wine runs out — a social catastrophe for the host family. Mary tells the servants to do whatever Jesus says. He has them fill six stone jars with water — jars used for Jewish purification rites, each holding twenty to thirty gallons. He tells them to draw some out and take it to the master of the banquet. The water has become wine. Not ordinary wine: the master says they have saved the best for last. This, the first of his signs, reveals his glory — and his disciples believe in him.",
      kjvText: "This beginning of miracles did Jesus in Cana of Galilee, and manifested forth his glory; and his disciples believed on him.",
      kjvRef: "John 2:11",
      scriptureRef: "John 2:1–11",
      approximateDate: "~28 AD"
    },
    {
      id: 6,
      section: "jesus",
      sequence: 6,
      type: "narrative",
      name: "Capernaum",
      modernName: "Kfar Nahum / Tell Hum, Israel",
      lat: 32.8806,
      lng: 35.5745,
      title: "Ministry Headquarters — 'His Own City'",
      summary: "Jesus makes Capernaum the center of his Galilean ministry — Matthew even calls it 'his own city.' It is a prosperous fishing town on the northwest shore of the Sea of Galilee. Here he calls Peter, Andrew, James, and John from their fishing boats. Here he heals Peter's mother-in-law, casts out an unclean spirit in the synagogue, and forgives and heals a paralytic lowered through a roof by four friends. He teaches with authority unlike the scribes. The town sees more miracles than almost anywhere else — and at the end, Jesus pronounces judgment on it for its unbelief.",
      kjvText: "And leaving Nazareth, he came and dwelt in Capernaum, which is upon the sea coast, in the borders of Zabulon and Nephthalim: That it might be fulfilled which was spoken by Esaias the prophet.",
      kjvRef: "Matthew 4:13–14",
      scriptureRef: "Matthew 4:13–22; Mark 1:21–34; Luke 4:31–41",
      approximateDate: "~28–30 AD"
    },
    {
      id: 7,
      section: "jesus",
      sequence: 7,
      type: "narrative",
      name: "Sea of Galilee",
      modernName: "Sea of Galilee (Kinneret), Israel",
      lat: 32.8321,
      lng: 35.5847,
      title: "Storms, Walking on Water, Miraculous Catch",
      summary: "The Sea of Galilee is the stage for some of Jesus' most striking demonstrations of power over creation. He calms a storm with three words while his terrified disciples ask: 'What manner of man is this, that even the wind and sea obey him?' He walks on the water in the fourth watch of the night, and reaches out to catch Peter when faith wavers. He directs a miraculous catch of fish that nearly sinks two boats. The lake the disciples know as their workplace becomes the classroom where they learn who they are following.",
      kjvText: "And he arose, and rebuked the wind, and said unto the sea, Peace, be still. And the wind ceased, and there was a great calm. And he said unto them, Why are ye so fearful? how is it that ye have no faith?",
      kjvRef: "Mark 4:39–40",
      scriptureRef: "Mark 4:35–41; Matthew 14:22–33; Luke 5:1–11",
      approximateDate: "~28–30 AD"
    },
    {
      id: 8,
      section: "jesus",
      sequence: 8,
      type: "narrative",
      name: "Caesarea Philippi",
      modernName: "Banias, Golan Heights, Israel",
      lat: 33.2500,
      lng: 35.6900,
      title: "Peter's Confession — 'Thou Art the Christ'",
      summary: "Jesus takes his disciples north to the region of Caesarea Philippi — a pagan city near Mount Hermon, site of a temple to Caesar and a shrine to Pan. Against this backdrop of imperial power and Greek religion, Jesus asks: who do people say that I am? Then: who do you say I am? Peter answers without hesitation — 'Thou art the Christ, the Son of the living God.' Jesus declares this was revealed by the Father, that on this rock he will build his church, and that the gates of hell will not prevail against it. Then he begins to tell them he must suffer and die.",
      kjvText: "He saith unto them, But whom say ye that I am? And Simon Peter answered and said, Thou art the Christ, the Son of the living God.",
      kjvRef: "Matthew 16:15–16",
      scriptureRef: "Matthew 16:13–20; Mark 8:27–30",
      approximateDate: "~29–30 AD"
    },
    {
      id: 9,
      section: "jesus",
      sequence: 9,
      type: "narrative",
      name: "Mount of Transfiguration",
      modernName: "Mount Hermon or Mount Tabor, Israel",
      lat: 32.6862,
      lng: 35.3906,
      title: "The Transfiguration",
      summary: "Six days after Peter's confession, Jesus takes Peter, James, and John up a high mountain. There, he is transfigured before them — his face shines like the sun, his clothes become dazzling white. Moses and Elijah appear and speak with him about his coming departure at Jerusalem. A cloud overshadows them and the Father's voice speaks again: 'This is my beloved Son, in whom I am well pleased; hear ye him.' The disciples fall on their faces in terror. Jesus touches them, and when they look up, they see only him. Coming down the mountain, he tells them to tell no one until after the Son of Man is raised from the dead.",
      kjvText: "And was transfigured before them: and his face did shine as the sun, and his raiment was white as the light. And, behold, there appeared unto them Moses and Elias talking with him.",
      kjvRef: "Matthew 17:2–3",
      scriptureRef: "Matthew 17:1–13; Mark 9:2–13; Luke 9:28–36",
      approximateDate: "~29–30 AD"
    },
    {
      id: 10,
      section: "jesus",
      sequence: 10,
      type: "narrative",
      name: "Jericho",
      modernName: "Jericho, West Bank",
      lat: 31.8667,
      lng: 35.4500,
      title: "Zacchaeus and Blind Bartimaeus",
      summary: "As Jesus approaches Jericho, a blind man named Bartimaeus cries out from the roadside: 'Jesus, thou Son of David, have mercy on me!' The crowd rebukes him. He cries louder. Jesus stops and calls him. 'What wilt thou that I shall do unto thee?' Receive my sight, Lord. It is done. In Jericho itself, the chief tax collector — Zacchaeus, too short to see over the crowd — has climbed a sycamore tree. Jesus stops beneath it, looks up, and invites himself to Zacchaeus's home. The whole city murmurs that he has gone to stay with a sinner. Zacchaeus announces he is giving half his goods to the poor and restoring fourfold what he has taken falsely.",
      kjvText: "And Jesus said unto him, This day is salvation come to this house, forsomuch as he also is a son of Abraham. For the Son of man is come to seek and to save that which was lost.",
      kjvRef: "Luke 19:9–10",
      scriptureRef: "Mark 10:46–52; Luke 19:1–10",
      approximateDate: "~30 AD"
    },
    {
      id: 11,
      section: "jesus",
      sequence: 11,
      type: "narrative",
      name: "Bethany",
      modernName: "Al-Eizariya, West Bank",
      lat: 31.7685,
      lng: 35.2626,
      title: "The Raising of Lazarus",
      summary: "Lazarus, the brother of Mary and Martha, falls ill. The sisters send word to Jesus — but he stays where he is for two more days. By the time he arrives, Lazarus has been in the tomb four days. Martha meets him on the road: 'Lord, if thou hadst been here, my brother had not died.' Jesus weeps. He goes to the tomb and commands the stone rolled away. He calls out in a loud voice: 'Lazarus, come forth.' The dead man walks out, still wrapped in burial cloths. Many believe. Some go to the Pharisees and report what has happened. From that day they plot to kill him.",
      kjvText: "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live: And whosoever liveth and believeth in me shall never die. Believest thou this?",
      kjvRef: "John 11:25–26",
      scriptureRef: "John 11:1–44",
      approximateDate: "~30 AD"
    },
    {
      id: 12,
      section: "jesus",
      sequence: 12,
      type: "narrative",
      name: "Jerusalem",
      modernName: "Jerusalem, Israel",
      lat: 31.7683,
      lng: 35.2137,
      title: "Entry, Temple, Last Supper, Trial, Cross, Resurrection",
      summary: "Jesus enters Jerusalem on a donkey while the crowd spreads cloaks and palm branches, crying Hosanna. He cleanses the temple of merchants and money-changers. He teaches in the temple courts daily while the chief priests seek to destroy him. He shares a final Passover meal with his disciples — taking bread and cup, establishing what will be remembered as the Lord's Supper. He prays in Gethsemane until sweat falls like drops of blood. He is betrayed, arrested, tried by Jewish leaders and then Pilate, beaten, crucified between two criminals. On the third day, the tomb is empty. He is seen alive — by Mary in the garden, by two on the road to Emmaus, by the disciples behind locked doors, by five hundred at once. He ascends from the Mount of Olives, promising to return.",
      kjvText: "He is not here: for he is risen, as he said. Come, see the place where the Lord lay.",
      kjvRef: "Matthew 28:6",
      scriptureRef: "Matthew 21–28; Mark 11–16; Luke 19–24; John 12–21",
      approximateDate: "~30 AD"
    }
  ],

  letters: [
    {
      id: 1,
      section: "letters",
      sequence: 1,
      type: "epistle-from",
      name: "Corinth",
      modernName: "Corinth, Greece",
      lat: 37.9387,
      lng: 22.9283,
      epistleName: "Romans",
      author: "Paul",
      writtenFromLabel: "Written from Corinth",
      writtenToLabel: "Written to Rome",
      writtenToLat: 41.9028,
      writtenToLng: 12.4964,
      approximateDate: "~AD 57",
      summary: "Paul writes his most systematic exposition of the gospel — justification by faith, the problem of sin, the hope of resurrection, the mystery of Israel, and the ethics of Christian community — to a church he has never visited, preparing to come in person after delivering relief funds to Jerusalem.",
      keyVerse: "For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth; to the Jew first, and also to the Greek.",
      keyRef: "Romans 1:16"
    },
    {
      id: 2,
      section: "letters",
      sequence: 2,
      type: "epistle-to",
      name: "Rome",
      modernName: "Rome, Italy",
      lat: 41.9028,
      lng: 12.4964,
      epistleName: "Romans",
      author: "Paul",
      writtenFromLabel: "Written from Corinth",
      writtenToLabel: "Written to Rome",
      writtenFromLat: 37.9387,
      writtenFromLng: 22.9283,
      approximateDate: "~AD 57",
      summary: "The church at Rome received Paul's most complete theological letter before ever meeting him in person. A mixed community of Jewish and Gentile believers, they had navigated tension and expulsion under Claudius. Paul addresses them as equals — in sin, in grace, in hope.",
      keyVerse: "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.",
      keyRef: "Romans 8:1"
    },
    {
      id: 3,
      section: "letters",
      sequence: 3,
      type: "epistle-from",
      name: "Ephesus",
      modernName: "Selçuk (near Ephesus), Turkey",
      lat: 37.9395,
      lng: 27.3417,
      epistleName: "1 Corinthians",
      author: "Paul",
      writtenFromLabel: "Written from Ephesus",
      writtenToLabel: "Written to Corinth",
      writtenToLat: 37.9387,
      writtenToLng: 22.9283,
      approximateDate: "~54–55 AD",
      summary: "Paul writes to address a church he founded that is fragmenting — divided by allegiances to different teachers, tolerating sexual immorality, abusing the Lord's Supper, confused about spiritual gifts, and doubting the resurrection. The letter contains his hymn to love in chapter 13 and the earliest written account of the resurrection appearances.",
      keyVerse: "And now abideth faith, hope, charity, these three; but the greatest of these is charity.",
      keyRef: "1 Corinthians 13:13"
    },
    {
      id: 4,
      section: "letters",
      sequence: 4,
      type: "epistle-from",
      name: "Macedonia",
      modernName: "Northern Greece / Macedonia region",
      lat: 40.9000,
      lng: 22.3800,
      epistleName: "2 Corinthians",
      author: "Paul",
      writtenFromLabel: "Written from Macedonia",
      writtenToLabel: "Written to Corinth",
      writtenToLat: 37.9387,
      writtenToLng: 22.9283,
      approximateDate: "~55–56 AD",
      summary: "Paul's most personal and emotionally raw letter — written in the wake of painful conflict with the Corinthian church. He defends his apostleship not with credentials but with suffering, defending the ministry of the new covenant and appealing for reconciliation. He speaks of a thorn in the flesh and the answer: 'My grace is sufficient for thee.'",
      keyVerse: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness.",
      keyRef: "2 Corinthians 12:9"
    },
    {
      id: 5,
      section: "letters",
      sequence: 5,
      type: "epistle-from",
      name: "Antioch (or uncertain)",
      modernName: "Antakya, Turkey",
      lat: 36.2021,
      lng: 36.1604,
      epistleName: "Galatians",
      author: "Paul",
      writtenFromLabel: "Written from Antioch (approximate)",
      writtenToLabel: "Written to churches of Galatia",
      writtenToLat: 38.5000,
      writtenToLng: 32.5000,
      approximateDate: "~48–55 AD",
      summary: "Paul is astonished — another gospel is being preached to the Galatians, requiring circumcision and law-keeping for justification. He defends his apostolic authority, recounts his confrontation with Peter, and argues with urgency that Christ has set believers free from the law as a means of salvation. 'There is neither Jew nor Greek... ye are all one in Christ Jesus.'",
      keyVerse: "Stand fast therefore in the liberty wherewith Christ hath made us free, and be not entangled again with the yoke of bondage.",
      keyRef: "Galatians 5:1"
    },
    {
      id: 6,
      section: "letters",
      sequence: 6,
      type: "epistle-from",
      name: "Rome",
      modernName: "Rome, Italy",
      lat: 41.9128,
      lng: 12.4864,
      epistleName: "Ephesians",
      author: "Paul",
      writtenFromLabel: "Written from Rome (prison)",
      writtenToLabel: "Written to Ephesus",
      writtenToLat: 37.9395,
      writtenToLng: 27.3417,
      approximateDate: "~AD 60–62",
      summary: "Written during Paul's Roman imprisonment, Ephesians soars with theology — the mystery of the church as Christ's body, Jews and Gentiles united in one new man, the armor of God for spiritual warfare. Paul prays for the readers to know the breadth, length, depth, and height of the love of Christ that surpasses knowledge.",
      keyVerse: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast.",
      keyRef: "Ephesians 2:8–9"
    },
    {
      id: 7,
      section: "letters",
      sequence: 7,
      type: "epistle-from",
      name: "Rome",
      modernName: "Rome, Italy",
      lat: 41.9228,
      lng: 12.5064,
      epistleName: "Philippians",
      author: "Paul",
      writtenFromLabel: "Written from Rome (prison)",
      writtenToLabel: "Written to Philippi",
      writtenToLat: 41.0137,
      writtenToLng: 24.2875,
      approximateDate: "~AD 60–62",
      summary: "Paul's most joyful letter, written while imprisoned, to the church that had supported him most faithfully — the first church planted in Europe. He tells them to rejoice always, to think on whatever is true and good and lovely, and that he has learned contentment in all circumstances. 'I can do all things through Christ which strengtheneth me.'",
      keyVerse: "I can do all things through Christ which strengtheneth me.",
      keyRef: "Philippians 4:13"
    },
    {
      id: 8,
      section: "letters",
      sequence: 8,
      type: "epistle-from",
      name: "Rome",
      modernName: "Rome, Italy",
      lat: 41.8928,
      lng: 12.4764,
      epistleName: "Colossians",
      author: "Paul",
      writtenFromLabel: "Written from Rome (prison)",
      writtenToLabel: "Written to Colossae",
      writtenToLat: 37.7700,
      writtenToLng: 29.1200,
      approximateDate: "~AD 60–62",
      summary: "Written to a church Paul may never have visited personally, to combat a philosophy mixing Jewish law-observance, angel worship, and asceticism with the gospel. Paul's answer is the supremacy of Christ — in whom all the fullness of the Godhead dwells bodily, in whom all treasure of wisdom and knowledge is hidden.",
      keyVerse: "For in him dwelleth all the fulness of the Godhead bodily. And ye are complete in him.",
      keyRef: "Colossians 2:9–10"
    },
    {
      id: 9,
      section: "letters",
      sequence: 9,
      type: "epistle-from",
      name: "Corinth",
      modernName: "Corinth, Greece",
      lat: 37.9487,
      lng: 22.9183,
      epistleName: "1 Thessalonians",
      author: "Paul",
      writtenFromLabel: "Written from Corinth",
      writtenToLabel: "Written to Thessalonica",
      writtenToLat: 40.6401,
      writtenToLng: 22.9444,
      approximateDate: "~AD 49–53",
      summary: "Likely Paul's earliest surviving letter, written shortly after being forced to leave Thessalonica and anxious about how the young church was faring under persecution. Timothy returns with good news: they are standing firm. Paul writes to encourage them, to address questions about believers who have died before Christ returns, and to call them to holiness.",
      keyVerse: "For the Lord himself shall descend from heaven with a shout, with the voice of the archangel, and with the trump of God: and the dead in Christ shall rise first.",
      keyRef: "1 Thessalonians 4:16"
    },
    {
      id: 10,
      section: "letters",
      sequence: 10,
      type: "epistle-from",
      name: "Corinth",
      modernName: "Corinth, Greece",
      lat: 37.9287,
      lng: 22.9383,
      epistleName: "2 Thessalonians",
      author: "Paul",
      writtenFromLabel: "Written from Corinth",
      writtenToLabel: "Written to Thessalonica",
      writtenToLat: 40.6401,
      writtenToLng: 22.9444,
      approximateDate: "~AD 49–53",
      summary: "A follow-up to the first letter, addressing confusion about whether the Day of the Lord has already come — which some were using as an excuse to stop working and become disruptive. Paul clarifies what must happen first and gives the practical instruction: 'If any would not work, neither should he eat.'",
      keyVerse: "But ye, brethren, be not weary in well doing.",
      keyRef: "2 Thessalonians 3:13"
    },
    {
      id: 11,
      section: "letters",
      sequence: 11,
      type: "epistle-from",
      name: "Macedonia",
      modernName: "Northern Greece / Macedonia region",
      lat: 40.9500,
      lng: 22.4200,
      epistleName: "1 Timothy",
      author: "Paul",
      writtenFromLabel: "Written from Macedonia",
      writtenToLabel: "Written to Timothy in Ephesus",
      writtenToLat: 37.9395,
      writtenToLng: 27.3417,
      approximateDate: "~63–65 AD",
      summary: "Paul writes to his son in the faith, left in Ephesus to deal with false teachers who have departed from sound doctrine. He gives instructions on prayer, on the qualifications of elders and deacons, on caring for widows, and on guarding the gospel entrusted to Timothy's keeping. 'Fight the good fight of faith.'",
      keyVerse: "Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called.",
      keyRef: "1 Timothy 6:12"
    },
    {
      id: 12,
      section: "letters",
      sequence: 12,
      type: "epistle-from",
      name: "Rome",
      modernName: "Rome, Italy",
      lat: 41.8828,
      lng: 12.4964,
      epistleName: "2 Timothy",
      author: "Paul",
      writtenFromLabel: "Written from Rome (final imprisonment)",
      writtenToLabel: "Written to Timothy in Ephesus",
      writtenToLat: 37.9395,
      writtenToLng: 27.3417,
      approximateDate: "~66–67 AD",
      summary: "Paul's final letter — written from prison, facing execution, with most friends gone. Demas has forsaken him, having loved this present world. He urges Timothy: preach the word, endure hardship, guard the gospel. He has fought the good fight, finished the course, kept the faith. A crown of righteousness awaits him. He asks Timothy to come before winter, and to bring the cloak he left at Troas.",
      keyVerse: "I have fought a good fight, I have finished my course, I have kept the faith: Henceforth there is laid up for me a crown of righteousness.",
      keyRef: "2 Timothy 4:7–8"
    },
    {
      id: 13,
      section: "letters",
      sequence: 13,
      type: "epistle-from",
      name: "Unknown location",
      modernName: "Location uncertain",
      lat: 37.0000,
      lng: 35.3213,
      epistleName: "Titus",
      author: "Paul",
      writtenFromLabel: "Written from uncertain location",
      writtenToLabel: "Written to Titus in Crete",
      writtenToLat: 35.2401,
      writtenToLng: 24.8093,
      approximateDate: "~63–65 AD",
      summary: "Paul writes to Titus, left on Crete to set in order what remains and appoint elders in every city. The letter emphasizes sound doctrine, the qualifications of church leaders, and the practical outworking of the gospel in conduct — especially against the backdrop of Crete's reputation for dishonesty.",
      keyVerse: "For the grace of God that bringeth salvation hath appeared to all men, Teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously, and godly, in this present world.",
      keyRef: "Titus 2:11–12"
    },
    {
      id: 14,
      section: "letters",
      sequence: 14,
      type: "epistle-from",
      name: "Rome",
      modernName: "Rome, Italy",
      lat: 41.9128,
      lng: 12.5164,
      epistleName: "Philemon",
      author: "Paul",
      writtenFromLabel: "Written from Rome (prison)",
      writtenToLabel: "Written to Philemon in Colossae",
      writtenToLat: 37.7700,
      writtenToLng: 29.1200,
      approximateDate: "~AD 60–62",
      summary: "Paul's shortest letter — a personal appeal on behalf of Onesimus, a slave who ran away from his master Philemon, somehow ended up with Paul in prison, and became a Christian. Paul sends him back with this letter: receive him no longer as a slave, but as a dear brother. Paul offers to repay any debt. He is confident Philemon will do even more than he asks.",
      keyVerse: "For perhaps he therefore departed for a season, that thou shouldest receive him for ever; Not now as a servant, but above a servant, a brother beloved.",
      keyRef: "Philemon 1:15–16"
    }
  ]
};
